services:
  app:
    image: ${DOCKERHUB_USERNAME}/chitchat-app:latest
    container_name: chitchat_app_production
    restart: unless-stopped
    working_dir: /var/www/chitchat
    env_file:
      - .env
    volumes:
      - chitchat_public_assets:/var/www/chitchat/public
    networks:
      - chitchat_network
      - global_routing_network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  # ARTIFAK BARU: Jalankan instans daemon Reverb Server
  reverb:
    image: ${DOCKERHUB_USERNAME}/chitchat-app:latest
    container_name: chitchat_reverb_production
    restart: unless-stopped
    working_dir: /var/www/chitchat
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - chitchat_network
      - global_routing_network
    depends_on:
      - app

  queue-worker:
    image: ${DOCKERHUB_USERNAME}/chitchat-app:latest
    container_name: chitchat_worker_production
    restart: unless-stopped
    working_dir: /var/www/chitchat
    # Jalankan worker secara konstan untuk menguras antrean di Redis
    command: php artisan queue:work --tries=3 --timeout=90
    env_file:
      - .env
    networks:
      - chitchat_network
    depends_on:
      - app
      - redis
  # ARTIFAK BARU: Redis sebagai driver Queue Broadcast Produksi
  redis:
    image: redis:alpine
    container_name: chitchat_redis_production
    restart: unless-stopped
    networks:
      - chitchat_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

  db:
    image: mysql:8.0
    container_name: chitchat_db_production
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - chitchat_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 3

networks:
  chitchat_network:
    driver: bridge
  global_routing_network:
    external: true

volumes:
  mysql_data:
  chitchat_public_assets:
