version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: chitchat_app
        restart: unless-stopped
        working_dir: /var/www/twitter-clone
        volumes:
            - /var/www/twitter-clone:/var/www/twitter-clone
        ports:
            - "127.0.0.1:9000:9000"
        extra_hosts:
            - "host.docker.internal:host-gateway"
