version: '3.8'

services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: chitchat_app
        restart: unless-stopped
        working_dir: /var/www/chitchat
        volumes:
            - .:/var/www/chitchat
        networks:
            - chitchat_network
        depends_on:
            db:
                condition: service_healthy


    webserver:
        image: nginx:alpine
        container_name: chitchat_web
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/chitchat
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
        networks:
            - chitchat_network
        depends_on:
            - app
    db:
        image: mysql:8.0
        container_name: chitchat_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: chitchat
        ports:
            -   "3306:3306"
        volumes:
            -   mysql_data:/var/lib/mysql
        restart: unless-stopped
        networks:
            - chitchat_network
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping"]
            interval: 3s
            timeout: 3s
            retries: 3
networks:
    chitchat_network:
        driver: bridge

volumes:
    mysql_data:
