services:
  app:
    image: ${DOCKERHUB_USERNAME}/chitchat-app:latest
    container_name: chitchat_app_production
    restart: unless-stopped
    working_dir: /var/www/chitchat
    # Paksa container membaca file .env hasil generate GitHub Actions di VPS
    env_file:
      - .env
    volumes:
      # Kita hanya membagikan folder public ke volume bersama agar dibaca Nginx
      - chitchat_public_assets:/var/www/chitchat/public
    networks:
      - chitchat_network
      - global_routing_network
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    container_name: chitchat_db_production
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - chitchat_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 3

networks:
  chitchat_network:
    driver: bridge
  global_routing_network:
    external: true

volumes:
  mysql_data:
  chitchat_public_assets:
