# HTTP & Certbot Challenge untuk Subdomain
server {
    listen 80;
    server_name chitchat.atabikm.me;

    error_log  /var/log/nginx/chitchat_error.log;
    access_log /var/log/nginx/chitchat_access.log;

    # Wajib ada agar Certbot bisa menerbitkan SSL untuk subdomain ini
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Sementara arahkan ke aplikasi sebelum SSL terbit
    root /var/www/chitchat/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000; # Pastikan container 'app' satu network dengan Nginx
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
